docker rm csgo_server_1
docker rm csgo_server_2
docker rm csgo_server_3
docker rm csgo_server_4
docker rm csgo_server_5
docker rm csgo_server_6
docker rm csgo_server_7
docker rm csgo_server_8
docker rm csgo_server_9
docker rm csgo_server_10
docker rm csgo_server_11
docker rm csgo_server_12
docker rm csgo_server_13
docker rm csgo_server_14
docker rm csgo_server_15
docker rm csgo_server_16
docker rm csgo_server_17
docker rm csgo_server_18
docker rm csgo_server_19
docker rm csgo_server_20
docker rm csgo_server_21
docker rm csgo_server_22
docker rm csgo_server_23
docker rm csgo_server_24
docker rm csgo_server_25
docker rm csgo_server_26
docker rm csgo_server_27
docker rm csgo_server_28
docker rm csgo_server_29
docker rm csgo_server_30
docker rm csgo_server_31
docker rm csgo_server_32
