bash csgo_server_1.sh
bash csgo_server_2.sh
bash csgo_server_3.sh
bash csgo_server_4.sh
bash csgo_server_5.sh
bash csgo_server_6.sh
bash csgo_server_7.sh
bash csgo_server_8.sh
bash csgo_server_9.sh
bash csgo_server_10.sh
bash csgo_server_11.sh
bash csgo_server_12.sh
bash csgo_server_13.sh
bash csgo_server_14.sh
bash csgo_server_15.sh
bash csgo_server_16.sh
bash csgo_server_17.sh
bash csgo_server_18.sh
bash csgo_server_19.sh
bash csgo_server_20.sh
bash csgo_server_21.sh
bash csgo_server_22.sh
bash csgo_server_23.sh
bash csgo_server_24.sh
bash csgo_server_25.sh
bash csgo_server_26.sh
bash csgo_server_27.sh
bash csgo_server_28.sh
bash csgo_server_29.sh
bash csgo_server_30.sh
bash csgo_server_31.sh
bash csgo_server_32.sh